#!/bin/bash

case "$1" in
"adapter")
    # we need something different in order to pass the classpath of the current project
    # you must specify: cluster name (and -zk param if different from localhost:2181) 
    
    # example : ./s4 adapter -cluster=c1
	shift 1
	<s4_install_dir>/gradlew cp
	java -cp `cat classpath.txt` org.apache.s4.core.S4Node $@
;;
*)
	echo "calling referenced s4 script : <s4_script_path>"
	(cd <s4_install_dir> && <s4_script_path> $@)
;;
esac